export const DISPLAY_ALERT = 'SHOW_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'

export const SETUP_USER_BEGIN = 'SETUP_USER_BEGIN'
export const SETUP_USER_SUCCESS = 'SETUP_USER_SUCCESS'
export const SETUP_USER_ERROR = 'SETUP_USER_ERROR'


export const LOGOUT_USER = 'LOGOUT_USER'

export const UPLOAD_IMAGE="UPLOAD_IMAGE"

export const HANDLE_CHANGE="HANDLE_CHANGE"

export const CLEAR_UPLOADS="CLEAR_UPLOADS"

export const SUBMIT_POST_BEGIN="SUBMIT_POST_BEGIN"
export const SUBMIT_POST_SUCCESS="SUBMIT_POST_SUCCESS"
export const SUBMIT_POST_ERROR="SUBMIT_POST_ERROR"


export const GET_Post_BEGIN="GET_POST_BEGIN"
export const GET_POST_SUCCESS="GET_POST_SUCCESS"
export const GET_POST_ERROR="GET_POST_ERROR"

export const CHANGE_PAGE="CHANGE_PAGE"



